---
- name: IOS_COMMANDS_PB
  hosts: routers
  gather_facts: false
  connection: local

  tasks:
   - name: show ip interface on routers
     ios_command:
       commands: show ip int br
     register: output

   - name: print output
     debug:
       var: output.stdout_lines